checkoutLocation: "go/src/github.com/olithissen/go-demo"
workspaceLocation: "go/src/github.com/olithissen/go-demo"
tasks:
  - command: >
      cd /workspace/go/src/github.com/olithissen/go-demo &&
      go get -v ./... 
